apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-admin
  annotations:
    {{- include "cms.annot" .Values.core.admin.service.annotations | nindent 4 }}
  labels:
    app: {{ .Release.Name }}-admin
    {{- include "cms.annot" .Values.core.admin.service.labels | nindent 4 }}
spec:
  type: {{ .Values.core.admin.service.type }}
  selector:
    app: {{ .Release.Name }}-core
  ports:
  - port: {{ .Values.core.admin.service.port }}
    targetPort: 8889
    {{- if eq .Values.core.admin.service.type "NodePort" }}
    nodePort: {{ .Values.core.admin.service.port }}
    {{- end }}
