{{- define "cms.genSecretKey" }}
{{- $source := randAscii 128 }}
{{- sha1sum $source | substr 0 32 }}
{{- end }}
{{- $secretName := printf "%s-secretkey" .Release.Name }}
{{- $previous := lookup "v1" "Secret" .Release.Namespace $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
type: Opaque
stringData:
{{- if $previous }}
  secretKey: {{ $previous.data.secretKey | b64dec }}
{{- else }}
  secretKey: {{ include "cms.genSecretKey" . }}
{{- end }}
